# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'KongFuCenter' do
pod "AFNetworking", "~> 2.0"
pod 'SVProgressHUD'
pod 'RongCloudIMKit', '2.4.0'
end

